<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Block' => 'Блок',
    'Block key' => 'Ключ блока',
    'Blocks' => 'Блоки',
    'Categories' => 'Категории',
    'Category' => 'Категория',
    'Category key' => 'Ключ категории',
    'Create' => 'Создать',
    'Key must be unique' => 'Ключ должен быть уникальным',
    'Page' => 'Страница',
    'Page key' => 'Ключ страницы',
    'Pages' => 'Страницы',
    'Save' => 'Сохранить',
    'Title' => 'Заголовок',
];
